version: 0.2

env:
  secrets-manager:
    DOCKER_TOKEN: "dockerhub-token:DOCKER_TOKEN"
phases:
  pre_build:
    commands:
      - echo "Cleaning workspace..."
      - rm -rf Devops_project

      - echo "Cloning repository..."
      - git clone https://github.com/tech98911023/Devops_project.git

  build:
    commands:
      - echo "Changing directory..."
      - cd Devops_project/TODO/src
      - echo "Logging into Docker Hub"
      - test -n "$DOCKER_TOKEN" && echo "Token is set" || echo "Token is EMPTY"
      - echo "$DOCKER_TOKEN" | docker login -u beginner9958 --password-stdin
      - echo "$DOCKER_USERNAME"

      - echo "Running docker compose..."
      - docker compose PUSH

  post_build:
    commands:
      - echo "Docker compose started successfully"
